/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jogo2;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Random;
import javax.swing.JOptionPane;

public class final_jogo extends javax.swing.JFrame {

    String res1;
    String res2;
    String res3;

    String nome;
    String resultado;

    public final_jogo() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p4 = new javax.swing.JPanel();
        resultado_final = new javax.swing.JLabel();
        jba2 = new javax.swing.JLabel();
        jba3 = new javax.swing.JLabel();
        cogu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultado_final.setBackground(new java.awt.Color(255, 255, 255));
        resultado_final.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        resultado_final.setForeground(new java.awt.Color(0, 0, 153));
        resultado_final.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultado_final.setText("RESULTADO");
        p4.add(resultado_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 380, 50));

        jba2.setBackground(new java.awt.Color(245, 239, 225));
        jba2.setFont(new java.awt.Font("Showcard Gothic", 1, 68)); // NOI18N
        jba2.setForeground(new java.awt.Color(0, 0, 102));
        jba2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jba2.setText("Final de ");
        p4.add(jba2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 370, 80));

        jba3.setBackground(new java.awt.Color(245, 239, 225));
        jba3.setFont(new java.awt.Font("Showcard Gothic", 1, 68)); // NOI18N
        jba3.setForeground(new java.awt.Color(0, 0, 102));
        jba3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jba3.setText("JOgo");
        p4.add(jba3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 210, 80));

        cogu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cogumelo.png"))); // NOI18N
        p4.add(cogu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        resultado_final.setText(resultadoF());
    }//GEN-LAST:event_formWindowActivated
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(final_jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(final_jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(final_jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(final_jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new final_jogo().setVisible(true);
            }
        });
    }

    public String resultadoF() {

        System.out.println("Partida 1: " + res1 + "\nPartida 2: " + res2 + "\nPartida 3: " + res3);

        if ((res1.equals("GANHOU") && res2.equals("GANHOU")) && res3.equals("PERDEU")) {
            resultado_final.setText("Parabéns Você ganhou");
            resultado = "Parabéns Você ganhou";
        } else if ((res1.equals("GANHOU") && res3.equals("GANHOU")) && res2.equals("PERDEU")) {
            resultado_final.setText("Parabéns Você ganhou");
            resultado = "Parabéns Você ganhou";
        } else if ((res2.equals("GANHOU") && res3.equals("GANHOU")) && res1.equals("PERDEU")) {
            resultado_final.setText("Parabéns Você ganhou");
            resultado = "Parabéns Você ganhou";
        } else if ((res1.equals("GANHOU") && res2.equals("GANHOU")) && res3.equals("GANHOU")) {
            resultado_final.setText("Parabéns Você ganhou");
            resultado = "Parabéns Você ganhou";
        } else {
            resultado_final.setText("Poxa Você Perdeu");
            resultado = "Poxa Você Perdeu";

        }
        conect.registergame(nome, resultado);
        return resultado;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cogu;
    private javax.swing.JLabel jba2;
    private javax.swing.JLabel jba3;
    private javax.swing.JPanel p4;
    private javax.swing.JLabel resultado_final;
    // End of variables declaration//GEN-END:variables

}
